[theme]
base = "dark"
primaryColor = "#ffffff"
backgroundColor = "#080808"
secondaryBackgroundColor = "#111111"
textColor = "#a0a0a0"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 30
